<?php

//Display 'create invoice page'
function attach_form_form($form,&$form_state){
  $form = array();
  
  //Select project name
  $query1 = db_select('node', 'n');
  $query1
         ->fields('n', array('type','title'))
         ->condition('n.type','project_entry');
  $result1 = $query1->execute();
  
  $projects = array();
  $projects[NULL] = '-Any-';
  foreach ($result1 as $value1) {
    $projects[$value1->title] = $value1->title;
  }
  
  $form['projects'] = array(
    '#type' => 'select',
    '#title' => 'Project Name',
    '#multiple' => TRUE,
    '#options' => $projects
  );
  
  $query2 = db_select('role', 'r');
  $query2
        ->fields('r', array('rid','name'))
        ->condition('r.name','administrator');
  $result2 = $query2->execute();
  $value2 = $result2->fetch();
       
  $query3 = db_select('users_roles', 'ur');
  $query3
        ->fields('ur', array('uid','rid'))
        ->condition('ur.rid',$value2->rid);
  $result3 = $query3->execute();
  $value3 = $result3->fetch();
       
  $query4 = db_select('users', 'us');
  $query4
        ->fields('us', array('uid','name'))
        ->condition('us.uid',$value3->uid);
  $result4 = $query4->execute();
  $value4 = $result4->fetch();
       
  $query5 = db_select('users', 'u');
  $query5->fields('u', array('name'));
  $result5 = $query5->execute();
       
  $members = array();
  $members[NULL] = '-Any-';
  //Assign user name to array with value and key for select list  
  foreach ($result5 as $value1) {
    if($value1->name != $value4->name){
      $members[$value1->name] = $value1->name;
    }        
  }
  
  $form['members'] = array(
    '#type' => 'select',
    '#title' => 'Members',
    '#multiple' => TRUE,
    '#options' => $members
  );
  
  $form['billable'] = array(
    '#type' => 'select',
    '#title' => 'Billable/Not Billable',
    '#options' => array(NULL => '-Any-','Billable' => 'Billable','Not Billable' => 'Not Billable')
  );
  
  $form['issues'] = array(
    '#id' => 'issuesfield',
    '#type' => 'textfield',
    '#title' => 'Issue Number'
  );
  
  $form['start'] = array(
    '#id' => 'startfield',
    '#type' => 'textfield',
    '#title' => 'Start Date',
    '#description' => 'E.g.,Y-m-d'
  );
    
  $form['end'] = array(
    '#id' => 'endfield',
    '#type' => 'textfield',
    '#title' => 'End Date',
    '#description' => 'E.g.,Y-m-d'
  );
  
  $form['apply'] = array(
    '#type' => 'button',
    '#value' => 'Apply'
  );
  
  $form['#submit'][] = 'submit_invoice';
  
  drupal_add_css(drupal_get_path('module', 'attach_view').'/attach_view.css');
  
  return $form;
}

//Move to 'invoice page' with nids whom checkbox select 
function submit_invoice($form,&$form_state){
  $nids = array();
  global $base_url;
  
  $keys = array_keys($form_state['values']['data']);
  $nodes = node_load_multiple($keys);
  foreach ($nodes as $node) {
    //Save invoice and assign key(nid) whose value not equal to zero
    if($form_state['values']['data'][$node->nid] != 0){
      $nids[] = $node->nid;
      $node->field_invoice['und'][0]['value'] = 'Invoice';
      node_save($node);
    }
  }
  $nid = implode(',', $nids);
  drupal_goto($base_url."/invoice/".$nid);
}
