<?php

function integrate_github_menu() {
  $items = array();  
  
  $items['github_info'] = array(
    'title' => t('Github Info'),
    'page callback' => 'github_info',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM
  ); 
  
  return $items;
}

function github_info(){
  $obj = json_decode($_POST['payload']);
  $message = $obj->repository->name;
  watchdog('Repository', $message);
}
